### ISSUE TITLE
中国語の再エディタでは表示が不十分です

### ISSUE THREAD

**Issue by yuyou040** [mitoma/kashiki2#67]
非常に面白いテキストエディタで、視覚効果は満点ですが、残念ながら中国語の出力をサポートしておらず、中国語の再エディタでは表示が不十分です。どのように修正すればよいですか?後期は国際化に対応しますか?
![image](https://github.com/user-attachments/assets/8190625b-f3ad-4bb7-b0b9-d31e6db07407)

**Comment by mitoma** [comment]
@yuyou040 
フィードバックありがとうございます。
現在のデフォルトのフォントは日本語フォントを使っていますが Windows であれば起動時のオプションでインストール済みのフォントを切り替えることができるようになっています。

```
kashikishi.exe -f "<font name>"
```

直接中国語フォントをバイナリに埋め込みたい場合は、以下の行で好みのフォントを指定すればよいでしょう。
https://github.com/mitoma/kashiki2/blob/main/kashikishi/src/main.rs#L48

国際化対応については今は計画していませんが、いずれ対応することを考慮した実装をしています。

**Comment by mitoma** [comment]
上記の回答で問題や疑問点は解決しましたか？

一度この issue は close しますが議論したい点があればこのチケットを参照して新しく issue を登録してください。
